[versions]

# --- ANDROID / CORE ---
activityCompose = "1.11.0"
agp = "8.13.0"
coreKtx = "1.17.0"
firebaseAuthKtxVersion = "23.2.1"
kernel = "9.3.0"
layout = "9.3.0"
lifecycleRuntimeKtx = "2.9.4"
runtime = "1.0.0-alpha07"

# --- CAMERA / MEDIA ---
cameraX = "1.5.1"

# --- COMPOSE / UI ---
composeBom = "2025.11.00"
composeCompiler = "2.2.21"
material3 = "1.4.0"
shimmer = "0.5.0"
uiText = "1.9.4"

# --- DATA / ROOM ---
roomCommonJvm = "2.8.3"
roomRuntimeAndroid = "2.8.3"
roomExternalAntlr = "2.8.3"

# --- FIREBASE / GOOGLE ---
firebaseAuthKtx = "24.0.1"
firebaseBom = "34.5.0"
firebaseCrashlyticsBuildtools = "3.0.6"
gson = "2.13.2"
litert = "2.0.3"
protoliteWellKnownTypes = "18.0.1"
transportationConsumer = "4.0.0"

# --- HILT / INYECCIÓN ---
hilt = "2.57.2"

# --- NAVIGATION ---
navigationCompose = "2.9.6"
navigationRuntimeAndroid = "2.9.6"

# --- OTROS / UTILIDADES / PRUEBAS ---
apriltag = "2025.3.1"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlin = "2.2.21"
poiOoxml = "5.4.1"
espressoCore = "3.7.0"

[libraries]

# --- ANDROID / CORE ---
androidx_activity_compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx_core_ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx_lifecycle_runtime_ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx_runtime = { group = "androidx.xr.runtime", name = "runtime", version.ref = "runtime" }

# --- CAMERA / MEDIA ---
androidx_camera_camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
androidx_camera_core = { module = "androidx.camera:camera-core", version.ref = "cameraX" }
androidx_camera_extensions = { module = "androidx.camera:camera-extensions", version.ref = "cameraX" }
androidx_camera_lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
androidx_camera_view = { module = "androidx.camera:camera-view", version.ref = "cameraX" }

# --- COMPOSE / UI ---
androidx_compose_bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx_material3 = { group = "androidx.compose.material3", name = "material3" }
androidx_ui = { group = "androidx.compose.ui", name = "ui" }
androidx_ui_graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx_ui_test_junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx_ui_test_manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx_ui_tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx_ui_tooling_preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtxVersion" }
kernel = { module = "com.itextpdf:kernel", version.ref = "kernel" }
layout = { module = "com.itextpdf:layout", version.ref = "layout" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }

# --- DATA / ROOM ---
androidx_room_common_jvm = { group = "androidx.room", name = "room-common-jvm", version.ref = "roomCommonJvm" }
androidx_room_runtime_android = { group = "androidx.room", name = "room-runtime-android", version.ref = "roomRuntimeAndroid" }
room-external-antlr = { group = "androidx.room", name = "room-external-antlr", version.ref = "roomExternalAntlr" }

# --- FIREBASE / GOOGLE ---
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase_bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase_crashlytics_buildtools = { group = "com.google.firebase", name = "firebase-crashlytics-buildtools", version.ref = "firebaseCrashlyticsBuildtools" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
litert = { group = "com.google.ai.edge.litert", name = "litert", version.ref = "litert" }
protolite-well-known-types = { group = "com.google.firebase", name = "protolite-well-known-types", version.ref = "protoliteWellKnownTypes" }
transportation-consumer = { group = "com.google.android.libraries.mapsplatform.transportation", name = "transportation-consumer", version.ref = "transportationConsumer" }

# --- HILT / INYECCIÓN ---
androidx_hilt_navigation_compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version = "1.3.0" }
hilt_android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt_android_compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# --- NAVIGATION ---
androidx_navigation_compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx_navigation_runtime_android = { group = "androidx.navigation", name = "navigation-runtime-android", version.ref = "navigationRuntimeAndroid" }

# --- OTROS / UTILIDADES / PRUEBAS ---
androidx_espresso_core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx_junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
apriltag_java = { group = "edu.wpi.first.apriltag", name = "apriltag-java", version.ref = "apriltag" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
poi_ooxml = { module = "org.apache.poi:poi-ooxml", version.ref = "poiOoxml" }


[plugins]

# --- ANDROID / KOTLIN ---
android_application = { id = "com.android.application", version.ref = "agp" }
kotlin_android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin_compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composeCompiler" }
kotlin_kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }

# --- HILT / INYECCIÓN ---
dagger_hilt_android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
